//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiCloudService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MDBResponseOfmClient3GCkhWO1", Namespace="http://schemas.datacontract.org/2004/07/Proveeduria.Apis.StructureResponse")]
    public partial class MDBResponseOfmClient3GCkhWO1 : object
    {
        
        private ApiCloudService.mClient bodyField;
        
        private string descriptionField;
        
        private int idField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ApiCloudService.mClient body
        {
            get
            {
                return this.bodyField;
            }
            set
            {
                this.bodyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.Runtime.Serialization.DataContractAttribute(Name="mClient", Namespace="http://schemas.datacontract.org/2004/07/Proveeduria.Apis.Models")]
    public partial class mClient : object
    {
        
        private System.Collections.Generic.List<ApiCloudService.mAccount> AccountField;
        
        private ApiCloudService.mAddress AddressField;
        
        private string CDNIField;
        
        private ApiCloudService.mClientType ClientTypeField;
        
        private long Cod_SigoClubField;
        
        private long CodeField;
        
        private string CommercialReasonField;
        
        private string CompanyNameField;
        
        private string DNIField;
        
        private System.DateTime DateUpdateField;
        
        private long DateUpdatemField;
        
        private string EmailField;
        
        private string FirstNameField;
        
        private char GenderField;
        
        private string LastNameField;
        
        private string MainPhoneField;
        
        private string MovilPhoneField;
        
        private string RifField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ApiCloudService.mAccount> Account
        {
            get
            {
                return this.AccountField;
            }
            set
            {
                this.AccountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ApiCloudService.mAddress Address
        {
            get
            {
                return this.AddressField;
            }
            set
            {
                this.AddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CDNI
        {
            get
            {
                return this.CDNIField;
            }
            set
            {
                this.CDNIField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ApiCloudService.mClientType ClientType
        {
            get
            {
                return this.ClientTypeField;
            }
            set
            {
                this.ClientTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Cod_SigoClub
        {
            get
            {
                return this.Cod_SigoClubField;
            }
            set
            {
                this.Cod_SigoClubField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CommercialReason
        {
            get
            {
                return this.CommercialReasonField;
            }
            set
            {
                this.CommercialReasonField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyName
        {
            get
            {
                return this.CompanyNameField;
            }
            set
            {
                this.CompanyNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DNI
        {
            get
            {
                return this.DNIField;
            }
            set
            {
                this.DNIField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateUpdate
        {
            get
            {
                return this.DateUpdateField;
            }
            set
            {
                this.DateUpdateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long DateUpdatem
        {
            get
            {
                return this.DateUpdatemField;
            }
            set
            {
                this.DateUpdatemField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public char Gender
        {
            get
            {
                return this.GenderField;
            }
            set
            {
                this.GenderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MainPhone
        {
            get
            {
                return this.MainPhoneField;
            }
            set
            {
                this.MainPhoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MovilPhone
        {
            get
            {
                return this.MovilPhoneField;
            }
            set
            {
                this.MovilPhoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Rif
        {
            get
            {
                return this.RifField;
            }
            set
            {
                this.RifField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.Runtime.Serialization.DataContractAttribute(Name="mAddress", Namespace="http://schemas.datacontract.org/2004/07/Proveeduria.Apis.Models")]
    public partial class mAddress : object
    {
        
        private string ApartmentField;
        
        private string AvenueField;
        
        private string BuildingField;
        
        private string FloorField;
        
        private string ReferencesField;
        
        private string StreetField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apartment
        {
            get
            {
                return this.ApartmentField;
            }
            set
            {
                this.ApartmentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Avenue
        {
            get
            {
                return this.AvenueField;
            }
            set
            {
                this.AvenueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Building
        {
            get
            {
                return this.BuildingField;
            }
            set
            {
                this.BuildingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Floor
        {
            get
            {
                return this.FloorField;
            }
            set
            {
                this.FloorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string References
        {
            get
            {
                return this.ReferencesField;
            }
            set
            {
                this.ReferencesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Street
        {
            get
            {
                return this.StreetField;
            }
            set
            {
                this.StreetField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.Runtime.Serialization.DataContractAttribute(Name="mClientType", Namespace="http://schemas.datacontract.org/2004/07/Proveeduria.Apis.Models")]
    public partial class mClientType : object
    {
        
        private int CodeField;
        
        private string DescriptionField;
        
        private string GroupField;
        
        private char IdentifierField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Group
        {
            get
            {
                return this.GroupField;
            }
            set
            {
                this.GroupField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public char Identifier
        {
            get
            {
                return this.IdentifierField;
            }
            set
            {
                this.IdentifierField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.Runtime.Serialization.DataContractAttribute(Name="mAccount", Namespace="http://schemas.datacontract.org/2004/07/Proveeduria.Apis.Models")]
    public partial class mAccount : object
    {
        
        private ApiCloudService.mAccountType AccountTypeField;
        
        private double BalanceField;
        
        private long Cod_SigoClubField;
        
        private int CodeField;
        
        private ApiCloudService.mMoney MoneyField;
        
        private long NumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ApiCloudService.mAccountType AccountType
        {
            get
            {
                return this.AccountTypeField;
            }
            set
            {
                this.AccountTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Balance
        {
            get
            {
                return this.BalanceField;
            }
            set
            {
                this.BalanceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Cod_SigoClub
        {
            get
            {
                return this.Cod_SigoClubField;
            }
            set
            {
                this.Cod_SigoClubField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ApiCloudService.mMoney Money
        {
            get
            {
                return this.MoneyField;
            }
            set
            {
                this.MoneyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Number
        {
            get
            {
                return this.NumberField;
            }
            set
            {
                this.NumberField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.Runtime.Serialization.DataContractAttribute(Name="mAccountType", Namespace="http://schemas.datacontract.org/2004/07/Proveeduria.Apis.Models")]
    public partial class mAccountType : object
    {
        
        private string AccountTypeField;
        
        private int CodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountType
        {
            get
            {
                return this.AccountTypeField;
            }
            set
            {
                this.AccountTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.Runtime.Serialization.DataContractAttribute(Name="mMoney", Namespace="http://schemas.datacontract.org/2004/07/Proveeduria.Apis.Models.Models")]
    public partial class mMoney : object
    {
        
        private int CodeField;
        
        private string EDICodeField;
        
        private string NameField;
        
        private string SymbolField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EDICode
        {
            get
            {
                return this.EDICodeField;
            }
            set
            {
                this.EDICodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Symbol
        {
            get
            {
                return this.SymbolField;
            }
            set
            {
                this.SymbolField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.Runtime.Serialization.DataContractAttribute(Name="mConsume", Namespace="http://schemas.datacontract.org/2004/07/Proveeduria.Apis.Models")]
    public partial class mConsume : object
    {
        
        private decimal AmountField;
        
        private long Cod_OperadorField;
        
        private ApiCloudService.mConsume.eTipoOperacionesMovimiento Cod_TipoOperacionMovField;
        
        private long NumberAccountField;
        
        private string NumberDocumentField;
        
        private decimal OldAmountField;
        
        private long SigoClubField;
        
        private string SucursalField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount
        {
            get
            {
                return this.AmountField;
            }
            set
            {
                this.AmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Cod_Operador
        {
            get
            {
                return this.Cod_OperadorField;
            }
            set
            {
                this.Cod_OperadorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ApiCloudService.mConsume.eTipoOperacionesMovimiento Cod_TipoOperacionMov
        {
            get
            {
                return this.Cod_TipoOperacionMovField;
            }
            set
            {
                this.Cod_TipoOperacionMovField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long NumberAccount
        {
            get
            {
                return this.NumberAccountField;
            }
            set
            {
                this.NumberAccountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumberDocument
        {
            get
            {
                return this.NumberDocumentField;
            }
            set
            {
                this.NumberDocumentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal OldAmount
        {
            get
            {
                return this.OldAmountField;
            }
            set
            {
                this.OldAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long SigoClub
        {
            get
            {
                return this.SigoClubField;
            }
            set
            {
                this.SigoClubField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sucursal
        {
            get
            {
                return this.SucursalField;
            }
            set
            {
                this.SucursalField = value;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
        [System.Runtime.Serialization.DataContractAttribute(Name="mConsume.eTipoOperacionesMovimiento", Namespace="http://schemas.datacontract.org/2004/07/Proveeduria.Apis.Models")]
        public enum eTipoOperacionesMovimiento : int
        {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            AbonoCambioCaja_NorkutPOS = 1,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            ConsumoFacturacion_NorkutPOS = 2,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            DevolucionFacturacion_NorkutPOS = 3,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            AbonoCambioCaja_InnovaPOS = 4,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            AbonoSaldoCaja_InnovaPOS = 5,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            ConsumoFacturacion_InnovaPOS = 6,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            DevolucionFacturacion_InnovaPOS = 7,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            DevolucionSaldoCaja_InnovaPOS = 8,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            AbonoDirectoSaldo_CRM = 9,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            AbonoGiftCard_CRM = 10,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            AbonoSaldoContrato_CRM = 11,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            ConsumoFacturacion_GS = 12,
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MDBResponseOflong", Namespace="http://schemas.datacontract.org/2004/07/Proveeduria.Apis.StructureResponse")]
    public partial class MDBResponseOflong : object
    {
        
        private long bodyField;
        
        private string descriptionField;
        
        private int idField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long body
        {
            get
            {
                return this.bodyField;
            }
            set
            {
                this.bodyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MDBResponseOfArrayOfKeyValueOflonglonguHEDJ7Dj", Namespace="http://schemas.datacontract.org/2004/07/Proveeduria.Apis.StructureResponse")]
    public partial class MDBResponseOfArrayOfKeyValueOflonglonguHEDJ7Dj : object
    {
        
        private System.Collections.Generic.Dictionary<long, long> bodyField;
        
        private string descriptionField;
        
        private int idField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<long, long> body
        {
            get
            {
                return this.bodyField;
            }
            set
            {
                this.bodyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MDBResponseOfArrayOfmMovement3GCkhWO1", Namespace="http://schemas.datacontract.org/2004/07/Proveeduria.Apis.StructureResponse")]
    public partial class MDBResponseOfArrayOfmMovement3GCkhWO1 : object
    {
        
        private System.Collections.Generic.List<ApiCloudService.mMovement> bodyField;
        
        private string descriptionField;
        
        private int idField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ApiCloudService.mMovement> body
        {
            get
            {
                return this.bodyField;
            }
            set
            {
                this.bodyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.Runtime.Serialization.DataContractAttribute(Name="mMovement", Namespace="http://schemas.datacontract.org/2004/07/Proveeduria.Apis.Models")]
    public partial class mMovement : object
    {
        
        private long AccountNumberField;
        
        private string AccountTypeField;
        
        private decimal AmountField;
        
        private string CDNIField;
        
        private char ClientTypeField;
        
        private int ClientTypeCodeField;
        
        private long Cod_MovementField;
        
        private long Cod_SigoClubField;
        
        private string Cod_SucField;
        
        private System.DateTime DateField;
        
        private long DatemField;
        
        private string DocumentField;
        
        private string NameField;
        
        private string TimeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long AccountNumber
        {
            get
            {
                return this.AccountNumberField;
            }
            set
            {
                this.AccountNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountType
        {
            get
            {
                return this.AccountTypeField;
            }
            set
            {
                this.AccountTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount
        {
            get
            {
                return this.AmountField;
            }
            set
            {
                this.AmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CDNI
        {
            get
            {
                return this.CDNIField;
            }
            set
            {
                this.CDNIField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public char ClientType
        {
            get
            {
                return this.ClientTypeField;
            }
            set
            {
                this.ClientTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClientTypeCode
        {
            get
            {
                return this.ClientTypeCodeField;
            }
            set
            {
                this.ClientTypeCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Cod_Movement
        {
            get
            {
                return this.Cod_MovementField;
            }
            set
            {
                this.Cod_MovementField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Cod_SigoClub
        {
            get
            {
                return this.Cod_SigoClubField;
            }
            set
            {
                this.Cod_SigoClubField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cod_Suc
        {
            get
            {
                return this.Cod_SucField;
            }
            set
            {
                this.Cod_SucField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date
        {
            get
            {
                return this.DateField;
            }
            set
            {
                this.DateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Datem
        {
            get
            {
                return this.DatemField;
            }
            set
            {
                this.DatemField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Document
        {
            get
            {
                return this.DocumentField;
            }
            set
            {
                this.DocumentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Time
        {
            get
            {
                return this.TimeField;
            }
            set
            {
                this.TimeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MDBResponseOfstring", Namespace="http://schemas.datacontract.org/2004/07/Proveeduria.Apis.StructureResponse")]
    public partial class MDBResponseOfstring : object
    {
        
        private string bodyField;
        
        private string descriptionField;
        
        private int idField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string body
        {
            get
            {
                return this.bodyField;
            }
            set
            {
                this.bodyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MDBResponseOfboolean", Namespace="http://schemas.datacontract.org/2004/07/Proveeduria.Apis.StructureResponse")]
    public partial class MDBResponseOfboolean : object
    {
        
        private bool bodyField;
        
        private string descriptionField;
        
        private int idField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool body
        {
            get
            {
                return this.bodyField;
            }
            set
            {
                this.bodyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MDBResponseOfArrayOfmClient3GCkhWO1", Namespace="http://schemas.datacontract.org/2004/07/Proveeduria.Apis.StructureResponse")]
    public partial class MDBResponseOfArrayOfmClient3GCkhWO1 : object
    {
        
        private System.Collections.Generic.List<ApiCloudService.mClient> bodyField;
        
        private string descriptionField;
        
        private int idField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ApiCloudService.mClient> body
        {
            get
            {
                return this.bodyField;
            }
            set
            {
                this.bodyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MDBResponseOfArrayOfmBasic3GCkhWO1", Namespace="http://schemas.datacontract.org/2004/07/Proveeduria.Apis.StructureResponse")]
    public partial class MDBResponseOfArrayOfmBasic3GCkhWO1 : object
    {
        
        private System.Collections.Generic.List<ApiCloudService.mBasic> bodyField;
        
        private string descriptionField;
        
        private int idField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ApiCloudService.mBasic> body
        {
            get
            {
                return this.bodyField;
            }
            set
            {
                this.bodyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.Runtime.Serialization.DataContractAttribute(Name="mBasic", Namespace="http://schemas.datacontract.org/2004/07/Proveeduria.Apis.Models")]
    public partial class mBasic : object
    {
        
        private long CodeField;
        
        private string CodeSField;
        
        private string DescriptionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodeS
        {
            get
            {
                return this.CodeSField;
            }
            set
            {
                this.CodeSField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ApiCloudService.IApiCloudService")]
    public interface IApiCloudService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApiCloudService/GetClientBalance", ReplyAction="http://tempuri.org/IApiCloudService/GetClientBalanceResponse")]
        System.Threading.Tasks.Task<ApiCloudService.MDBResponseOfmClient3GCkhWO1> GetClientBalanceAsync(int pType, string pDocument);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApiCloudService/ConsumePoints", ReplyAction="http://tempuri.org/IApiCloudService/ConsumePointsResponse")]
        System.Threading.Tasks.Task<ApiCloudService.MDBResponseOflong> ConsumePointsAsync(long pSigoClub, string pSucursal, long pNumberAccount, string pNumberDocument, decimal pOldAmount, decimal amount, long Cod_Operador, ApiCloudService.mConsume.eTipoOperacionesMovimiento Cod_TipoOperacionMov);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApiCloudService/ConsumePointsL", ReplyAction="http://tempuri.org/IApiCloudService/ConsumePointsLResponse")]
        System.Threading.Tasks.Task<ApiCloudService.MDBResponseOfArrayOfKeyValueOflonglonguHEDJ7Dj> ConsumePointsLAsync(System.Collections.Generic.List<ApiCloudService.mConsume> pConsumes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApiCloudService/GetHistoricMovements", ReplyAction="http://tempuri.org/IApiCloudService/GetHistoricMovementsResponse")]
        System.Threading.Tasks.Task<ApiCloudService.MDBResponseOfArrayOfmMovement3GCkhWO1> GetHistoricMovementsAsync(string pSucursal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApiCloudService/GetDataProductSync", ReplyAction="http://tempuri.org/IApiCloudService/GetDataProductSyncResponse")]
        System.Threading.Tasks.Task<ApiCloudService.MDBResponseOfstring> GetDataProductSyncAsync(long pDate, string pSucursal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApiCloudService/GetDataRateSync", ReplyAction="http://tempuri.org/IApiCloudService/GetDataRateSyncResponse")]
        System.Threading.Tasks.Task<ApiCloudService.MDBResponseOfstring> GetDataRateSyncAsync(long pDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApiCloudService/GetDataTransferSync", ReplyAction="http://tempuri.org/IApiCloudService/GetDataTransferSyncResponse")]
        System.Threading.Tasks.Task<ApiCloudService.MDBResponseOfstring> GetDataTransferSyncAsync(long pDate, string pSucursal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApiCloudService/ConfirmPass", ReplyAction="http://tempuri.org/IApiCloudService/ConfirmPassResponse")]
        System.Threading.Tasks.Task<ApiCloudService.MDBResponseOfboolean> ConfirmPassAsync(long pUsuario, string pPass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApiCloudService/GetClientsCompany", ReplyAction="http://tempuri.org/IApiCloudService/GetClientsCompanyResponse")]
        System.Threading.Tasks.Task<ApiCloudService.MDBResponseOfArrayOfmClient3GCkhWO1> GetClientsCompanyAsync(long pCodSIGOClub);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApiCloudService/GetConsumePointsGraph", ReplyAction="http://tempuri.org/IApiCloudService/GetConsumePointsGraphResponse")]
        System.Threading.Tasks.Task<ApiCloudService.MDBResponseOfArrayOfmBasic3GCkhWO1> GetConsumePointsGraphAsync(string pSucursal, long pStart, long pEnd);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    public interface IApiCloudServiceChannel : ApiCloudService.IApiCloudService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30422-0661")]
    public partial class ApiCloudServiceClient : System.ServiceModel.ClientBase<ApiCloudService.IApiCloudService>, ApiCloudService.IApiCloudService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ApiCloudServiceClient() : 
                base(ApiCloudServiceClient.GetDefaultBinding(), ApiCloudServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IApiCloudService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ApiCloudServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(ApiCloudServiceClient.GetBindingForEndpoint(endpointConfiguration), ApiCloudServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ApiCloudServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ApiCloudServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ApiCloudServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ApiCloudServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ApiCloudServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ApiCloudService.MDBResponseOfmClient3GCkhWO1> GetClientBalanceAsync(int pType, string pDocument)
        {
            return base.Channel.GetClientBalanceAsync(pType, pDocument);
        }
        
        public System.Threading.Tasks.Task<ApiCloudService.MDBResponseOflong> ConsumePointsAsync(long pSigoClub, string pSucursal, long pNumberAccount, string pNumberDocument, decimal pOldAmount, decimal amount, long Cod_Operador, ApiCloudService.mConsume.eTipoOperacionesMovimiento Cod_TipoOperacionMov)
        {
            return base.Channel.ConsumePointsAsync(pSigoClub, pSucursal, pNumberAccount, pNumberDocument, pOldAmount, amount, Cod_Operador, Cod_TipoOperacionMov);
        }
        
        public System.Threading.Tasks.Task<ApiCloudService.MDBResponseOfArrayOfKeyValueOflonglonguHEDJ7Dj> ConsumePointsLAsync(System.Collections.Generic.List<ApiCloudService.mConsume> pConsumes)
        {
            return base.Channel.ConsumePointsLAsync(pConsumes);
        }
        
        public System.Threading.Tasks.Task<ApiCloudService.MDBResponseOfArrayOfmMovement3GCkhWO1> GetHistoricMovementsAsync(string pSucursal)
        {
            return base.Channel.GetHistoricMovementsAsync(pSucursal);
        }
        
        public System.Threading.Tasks.Task<ApiCloudService.MDBResponseOfstring> GetDataProductSyncAsync(long pDate, string pSucursal)
        {
            return base.Channel.GetDataProductSyncAsync(pDate, pSucursal);
        }
        
        public System.Threading.Tasks.Task<ApiCloudService.MDBResponseOfstring> GetDataRateSyncAsync(long pDate)
        {
            return base.Channel.GetDataRateSyncAsync(pDate);
        }
        
        public System.Threading.Tasks.Task<ApiCloudService.MDBResponseOfstring> GetDataTransferSyncAsync(long pDate, string pSucursal)
        {
            return base.Channel.GetDataTransferSyncAsync(pDate, pSucursal);
        }
        
        public System.Threading.Tasks.Task<ApiCloudService.MDBResponseOfboolean> ConfirmPassAsync(long pUsuario, string pPass)
        {
            return base.Channel.ConfirmPassAsync(pUsuario, pPass);
        }
        
        public System.Threading.Tasks.Task<ApiCloudService.MDBResponseOfArrayOfmClient3GCkhWO1> GetClientsCompanyAsync(long pCodSIGOClub)
        {
            return base.Channel.GetClientsCompanyAsync(pCodSIGOClub);
        }
        
        public System.Threading.Tasks.Task<ApiCloudService.MDBResponseOfArrayOfmBasic3GCkhWO1> GetConsumePointsGraphAsync(string pSucursal, long pStart, long pEnd)
        {
            return base.Channel.GetConsumePointsGraphAsync(pSucursal, pStart, pEnd);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IApiCloudService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IApiCloudService))
            {
                return new System.ServiceModel.EndpointAddress("http://proveeduriasdesiis.norkut.com.ve/CloudServices/ApiCloudService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ApiCloudServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IApiCloudService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ApiCloudServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IApiCloudService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IApiCloudService,
        }
    }
}
